# Generated by Django 5.1.1 on 2024-12-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoo',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
